import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/report_model.dart';

class PdfService {
  static Future<void> generateAndPrintReport(ReportModel report) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('MindEase', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                    pw.Text('Mental Health Report', style: pw.TextStyle(fontSize: 18, color: PdfColors.grey700)),
                  ],
                ),
                pw.SizedBox(height: 10),
                pw.Divider(color: PdfColors.teal, thickness: 2),
                pw.SizedBox(height: 20),
                
                pw.Row(
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Patient Name:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text(report.name),
                      ],
                    ),
                    pw.Spacer(),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Analysis Date:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text(report.date),
                      ],
                    ),
                  ],
                ),
                
                pw.SizedBox(height: 30),
                pw.Text('Stress Analysis Results', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                
                pw.TableHelper.fromTextArray(
                  context: context,
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
                  data: [
                    ['Modality', 'Score (%)'],
                    ['Face Recognition', '${report.face}%'],
                    ['Voice Analysis', '${report.voice}%'],
                    ['Text Sentiment', '${report.text}%'],
                    ['COMPOSITE STRESS', '${report.combined}%'],
                  ],
                ),
                
                pw.SizedBox(height: 30),
                pw.Text('Detected Primary Emotion:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.Text(report.emotion),
                
                pw.SizedBox(height: 20),
                pw.Text('Primary Stress Factors (Reason):', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.Text(report.reason),
                
                pw.SizedBox(height: 20),
                pw.Text('Long-term Projection (Future Simulation):', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.Text(report.future),
                
                pw.Spacer(),
                pw.Divider(color: PdfColors.grey300),
                pw.Align(
                  alignment: pw.Alignment.center,
                  child: pw.Text('Generated by MindEase AI', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic)),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'MindEase_Report_${report.date.replaceAll(' ', '_')}.pdf',
    );
  }
}
